about/urls.py
from django.urls import path

from . import views

app_name = "about"

urlpatterns = [
    path("author/", views.AboutAuthorView.as_view(), name="author"),
    path("tech/", views.AboutTechView.as_view(), name="tech"),
]

yatube/urls.py
from django.conf import settings
from django.conf.urls import handler404, handler500
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path("about/", include("about.urls", namespace="about")),
    path("auth/", include("users.urls")),
    path("auth/", include("django.contrib.auth.urls")),
    path("admin/", admin.site.urls),
    path("", include("posts.urls")),
    path("404", handler404),
    path("500", handler500),
]

handler404 = "posts.views.page_not_found"  # noqa
handler500 = "posts.views.server_error"  # noqa

if settings.DEBUG:
    import debug_toolbar
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL,
                          document_root=settings.STATIC_ROOT)
    urlpatterns += (path("__debug__/", include(debug_toolbar.urls)),)

templates/include/bio_column.html
<div class="col-md-3 mb-3 mt-1">
  <div class="card">
    <div class="card-body">
      <div class="h2">
        {{ author.get_full_name }}
      </div>
      <div class="h3 text-muted">
        @{{ author.username }}
      </div>
    </div>
    <ul class="list-group list-group-flush">
      <li class="list-group-item">
        <div class="h6 text-muted">
          Подписчиков: {{ followers }} <br />
          Подписан: {{ following }}
        </div>
      </li>
      <li class="list-group-item">
        <div class="h6 text-muted">
          Записей: {{ posts_amount }}
        </div>
      </li>
      {% if author != request.user %}
      <li class="list-group-item">
        {% if following_status %}
        <a class="btn btn-lg btn-light" href="{% url 'profile_unfollow' author.username %}" role="button">
          Отписаться
        </a>
        {% else %}

        <a class="btn btn-lg btn-primary" href="{% url 'profile_follow' author.username %}" role="button">
          Подписаться
        </a>

        {% endif %}
      </li>
      {% endif %}
    </ul>
  </div>
</div>

templates/include/comments.html
{% load user_filters %}
{% for item in comments %}
<div class="media card mb-4">
  <div class="media-body card-body">
    <h5 class="mt-0">
      <a href="{% url 'profile' item.author.username %}" name="comment_{{ item.id }}">
        {{ item.author.username }}
      </a>
    </h5>
    <p>{{ item.text | linebreaksbr }}</p>
    <div class="d-flex justify-content-between align-items-center">
      {% if user.is_authenticated %}
      {% if user.username == item.author.username %}
      <a class="btn btn-sm text-muted" href="{% url 'comment_delete' post.author.username post.id item.id %}" role="button">Удалить комментарий </a>
      {% endif %}
      {% endif %}
    </div>
  </div>
</div>
{% empty %}
<p>Комментариев пока нет :(</p>
{% endfor %}

templates/include/footer.html
<footer class="pt-4 my-md-5 pt-md-5 border-top">
  <p class="m-0 text-dark text-center ">
    <a href=" {% url 'about:author' %}"><span style="color:#FF7D75">Об авторе</span></a>
    <span style="color:#FF7D75"> |</span>
    <a href=" {% url 'about:tech' %}"><span style="color:#FF7D75">Технологии</span></a>
  </p>
  <p class="m-0 text-dark text-center ">Социальная сеть <span style="color:#FF7D75">Fi</span>ji © {{ year }}, все права защищены.</p>
</footer>

templates/include/menu.html
{% if user.is_authenticated %}
<div class="row">
  <ul class="nav nav-tabs">
    <li class="nav-item">
      <a class="nav-link {% if index %}active{% endif %}" href="{% url 'index' %}">
        Все авторы
      </a>
    </li>
    <li class="nav-item">
      <a class="nav-link text-dark {% if follow %}active{% endif %}" href="/follow">
        Избранные авторы
      </a>
    </li>
  </ul>
</div>
{% endif %}

templates/include/nav.html
{% load static %}
<div class="container">
  <header class="blog-header py-3">
    <div class="row flex-nowrap justify-content-between align-items-center">
      <div class="col-4 pt-1">
        <a class="text-muted" href="/">Home</a>
      </div>
      <div class="col-4 text-center">
        <a class="blog-header-logo text-dark" href="/"><span style="color:#000000;font:80pt bold NEW YORK;">FIJI</span></a>
      </div>
      <div class="col-4 d-flex justify-content-end align-items-center">
        <a class="text-muted" href="#">
          <svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" class="mx-3" role="img" viewBox="0 0 24 24" focusable="false">
            <title>Search</title>
            <circle cx="10.5" cy="10.5" r="7.5"></circle>
            <path d="M21 21l-5.2-5.2"></path>
          </svg>
        </a>
        {% if user.is_authenticated %}
        <a class="text-dark">Пользователь: {{ user.username }}.</a>
        <a class="btn btn-sm btn-outline-secondary" href="{% url 'new_post' %}">Новая запись</a>
        <a class="btn btn-sm btn-outline-secondary" href="{% url 'password_change' %}">Изменить пароль</a>
        <a class="btn btn-sm btn-outline-secondary" href="{% url 'logout' %}">Выйти</a>
        {% else %}
        <a class="btn btn-sm btn-outline-secondary" href="{% url 'login' %}">Войти</a>
        <a class="btn btn-sm btn-outline-secondary" href="{% url 'signup' %}">Регистрация</a>
        {% endif %}
      </div>
    </div>
  </header>
  <div class="nav-scroller py-1 mb-2">
    <nav class="nav d-flex justify-content-between">
      <a class="p-2 text-muted" href="/group/fiji/">Fiji</a>
      <a class="p-2 text-muted" href="/group/yandex/">Yandex</a>
      <a class="p-2 text-muted" href="/group/technology/">Technology</a>
      <a class="p-2 text-muted" href="/group/design/">Design</a>
      <a class="p-2 text-muted" href="/group/culture/">Culture</a>
      <a class="p-2 text-muted" href="/group/business/">Business</a>
      <a class="p-2 text-muted" href="/group/politics/">Politics</a>
      <a class="p-2 text-muted" href="/group/opinion/">Opinion</a>
      <a class="p-2 text-muted" href="/group/science/">Science</a>
      <a class="p-2 text-muted" href="/group/health/">Health</a>
      <a class="p-2 text-muted" href="/group/style/">Style</a>
      <a class="p-2 text-muted" href="/group/travel/">Travel</a>
    </nav>
  </div>
</div>

templates/include/new_comment.html
{% load user_filters %}

{% if user.is_authenticated %}
<div class="card my-4">
  <form method="post" action="{% url 'add_comment' author.username post.id %}">
    {% csrf_token %}
    <h5 class="card-header">Добавить комментарий:</h5>
    <div class="card-body">
      <div class="form-group">
        {{ form.text|addclass:"form-control"}}
      </div>
      <button type="submit" class="btn btn-primary">Отправить</button>
    </div>
  </form>
</div>
{% endif %}

templates/include/paginator.html
{% if page.has_other_pages %}
<nav>
  <ul class="pagination justify-content-center">
    {% if page.has_previous %}
    <li class="page-item">
      <a class="page-link" style="color:#FF7D75" href="?page={{ page.previous_page_number }}">&laquo; Предыдущая</a>
    </li>
    {% else %}
    <li class="page-item disabled">
      <span class="page-link">&laquo; Предыдущая</span>
    </li>
    {% endif %}
    {% for i in page.paginator.page_range %}
    {% if page.number == i %}
    <li class="page-item active">
      <span class="page-link">{{ i }}
        <span class="sr-only" style="color:#FF7D75">(текущая)</span>
      </span>
    </li>
    {% else %}
    <li class="page-item">
      <a class="page-link" style="color:#FF7D75" href="?page={{ i }}">{{ i }}</a>
    </li>
    {% endif %}
    {% endfor %}
    {% if page.has_next %}
    <li class="page-item">
      <a class="page-link" style="color:#FF7D75" href="?page={{ page.next_page_number }}">Следующая &raquo;</a>
    </li>
    {% else %}
    <li class="page-item disabled">
      <span class="page-link">Следующая &raquo;</span>
    </li>
    {% endif %}
  </ul>
</nav>
{% endif %}

templates/include/post_item.html
<div class="col-md-8 blog-main">
  <h3 class="pb-4 mb-4 font-italic border-bottom">
    {% if post.group %}
    <a class="card-link muted" href="{% url 'group' post.group.slug %}">
      <strong class="d-block" style="color: #7CDAB8;">#{{ post.group.title }}</strong>
    </a>
    {% endif %}
  </h3>
  <div class="blog-post">
    <h2 class="blog-post-title">{{ post.title }}</h2>
    <p class="blog-post-meta">{{ post.pub_date }} by <a href="{% url 'profile' post.author.username %}"><strong style="color:#FF7D75">@{{ post.author }}</strong>
      </a>
    </p>

    <p>{% load thumbnail %}
      {% thumbnail post.image "960x339" crop="center" upscale=True as im %}
      <img class="card-img" src="{{ im.url }}">
      {% endthumbnail %}</p>
    <p>{{ post.text|linebreaksbr }}</p>
    <p>
      <a href="{% url 'post' post.author.username post.id%}" class="btn btn-sm text-muted" role="button">Комментариев: {{ post.comments.count }}</a>
      {% url 'post' post.author.username post.id as the_url %}
      {% if request.get_full_path == the_url %}
      {% if user.is_authenticated %}
      {% if user.username == post.author.username %}
      <a href="{% url 'post_edit' post.author.username post.id%}" class="btn btn-sm text-muted">Редактировать</a>
      <a href="{% url 'post_delete' post.author.username post.id %}" class="btn btn-sm text-muted">Удалить</a>
      {% endif %}
      {% endif %}
      {% endif %}
    </p>
  </div>
</div>

templates/include/sidebar.html
{% load static %}
<aside class="col-md-4 blog-sidebar">
  <div class="p-4">
    <ol class="list-unstyled">
      <a href="https://github.com/nazarovaea1"><img src="{% static '/images/github100.png' %}" width="35px" height="35px" alt="Github"></a>
      <a href="tg://resolve?domain=nazarovaea"><img src="{% static '/images/telegram128.png' %}" width="35px" height="35px" alt="Telegram"></a>
      <a href="https://www.instagram.com/nazarovaea/"><img src="{% static '/images/instagram128.png' %}" width="35px" height="35px" alt="Instagram"></a>
      <a href="mailto:nazarovaea1@gmail.com"><img src="{% static '/images/mail128.png' %}" width="35px" height="35px" alt="Mail"></a>
    </ol>
  </div>
</aside>